# Generated by Django 5.1.1 on 2024-10-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_status',
            field=models.BooleanField(default=False),
        ),
    ]
