# Generated by Django 5.1.1 on 2024-10-06 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.table'),
            preserve_default=False,
        ),
    ]
