# Generated by Django 5.1.1 on 2024-10-06 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_table_table_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.table'),
        ),
    ]
