# Generated by Django 5.1.1 on 2024-10-06 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_remove_customer_address_alter_customer_email_and_more'),
        ('orders', '0005_alter_order_order_no_alter_orderitem_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='total',
            field=models.FloatField(blank=True),
        ),
    ]
